spring:
  application:
    name: utils
    starter-log: true # Show Started Application
app:
  version: @project.version@ # Show Project Version
  shouldNotFilter: "/swagger-ui/index.html,/swagger-ui/swagger-initializer.js,/v3/api-docs,/v3/api-docs/**"
  exception:
    stacktrace: true # Active StackTrace in Response
  # Cors status
  cors: # Disabled
    enabled: false

# Level of LOG
logging:
  logback:
    logTail: # Logging on LogTail
      active: false
    google-cloud: # Logging on Google
      active: false
  level:
    io.github.giovannilamarmora.utils: INFO # Use DEBUG for access to LogTimeTracker LOGS
    web: ERROR
    root: INFO
    org:
      springframework:
        web: ERROR
      hibernate: ERROR

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    
rest:
  webClient:
    timeout:
      read: 15000
      write: 15000
      connection: 10000

management:
  info:
    enabled: true
  env:
    enable: true
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,loggers
