env: Local # Used for Google Cloud LOG
spring:
  application:
    name: utils
    starter-log: true # Show Started Application
app:
  version: @project.version@ # Show Project Version
  shouldNotFilter: "**/swagger-ui/**,/api-docs,**/api-docs/**,*/,*.css,*.js,*/img/*,*/favicon.ico"
  exception:
    stacktrace: true # Active StackTrace in Response
  # Cors status
  cors: # Disabled
    enabled: false

# Level of LOG
logging:
  config: classpath:logback-spring.xml # classpath:logback-google.xml, classpath:logback-logtail.xml
  level:
    io.github.giovannilamarmora.utils: INFO # Use DEBUG for access to LogTimeTracker LOGS
    web: ERROR
    root: INFO
    org:
      springframework:
        web: ERROR
      hibernate: ERROR

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

rest:
  webClient:
    timeout:
      read: 15000
      write: 15000
      connection: 10000

filter:
  requestResponse:
    enabled: false
    shouldNotFilter: "**/swagger-ui/**,/api-docs,**/api-docs/**,*/,*.css,*.js,*/img/*,*/favicon.ico"

management:
  info:
    enabled: true
  env:
    enable: true
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,loggers
