app:
  version: @project.version@
  shouldNotFilter: "/swagger-ui/index.html,/swagger-ui/swagger-initializer.js,/v3/api-docs,/v3/api-docs/**"
  exception:
    stacktrace: true # Active StackTrace in Response
  # Cors status
  cors: # Disabled
    enabled: false
  # Logging on LogTail
  logTail: # Disabled
    active: false
    level: INFO # Keep as INFO and work on logging instead (testa in caso rimuovi)

# Level of LOG
logging:
  level:
    io.github.giovannilamarmora.utils: INFO # Use DEBUG for access to LogTimeTracker LOGS
    web: ERROR
    root: INFO
    org:
      springframework:
        web: ERROR
      hibernate: ERROR

rest:
  webClient:
    timeout:
      read: 15000
      write: 15000
      connection: 10000

management:
  info:
    enabled: true
  env:
    enable: true
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,loggers
