# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package Deploy Show

on:
  push:
    branches: [ develop ]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up secret file
        run: |
          echo ${{ secrets.MAVEN_USER_NAME }} | sed 's/./& /g'
          echo ${{ secrets.MAVEN_ACCESS_TOKEN }} | sed 's/./& /g'